### ISSUE TITLE
Disable taps on content elements

### ISSUE THREAD

**Issue by alibasta** [medyas/flutter_zoom_drawer#10]
Thanks for this great flutter menu!
I'm wondering how you would disable taps on the content page while the menu is open. I experienced some problems with buttons on the content page being tappable while the menu is open and I would like to deactivate them if the drawer is visible.
Thanks!

**Comment by medyas** [comment]
Hi, thanks for the feedback.
To stop receiving gestures in the main content when the drawer is open, you can wrap you content with [`AbsorbPointer `](https://api.flutter.dev/flutter/widgets/AbsorbPointer-class.html) widget.

The `AbsorbPointer`, `absorbing ` parameter, if set to `true `it will deactivate all event made to the child widget. so you can update the value of absorbing ` based on the current state of the drawer.

```
AbsorbPointer(
  absorbing: _absorbing,
  child: Main_Content,
)
```

**Comment by alibasta** [comment]
Thanks! Thats exactly what I've already tried so far. The problem ist that the `isOpen()` is updated after the second tap when I tested it. Thats what I added inside my draw container inside `return NotificationListener()`:
```
AbsorbPointer(
                  absorbing: _drawerController.isOpen(),
                  child: loadPage(_currentPage, _pageParams)
              )
```

**Comment by medyas** [comment]
Hi, I have updated the package [[`flutter_zoom_drawer: ^1.0.4`](https://pub.dev/packages/flutter_zoom_drawer#-readme-tab-)] and added a `ValueListener `with the drawer state which allows you to be notified of the state updates and can update you widgets accordingly.
Here is the updated example

```
return ValueListenableBuilder<DrawerState>(
      valueListenable: ZoomDrawer.of(context).stateNotifier,
      builder: (context, state, child) {
        return AbsorbPointer(
          absorbing: state != DrawerState.closed,
          child: child,
        );
      },
      child: GestureDetector(
        child: PageStructure(),
        onPanUpdate: (details) {
          if (details.delta.dx < 6 && !rtl || details.delta.dx < -6 && rtl) {
            ZoomDrawer.of(context).toggle();
          }
        },
      ),
    ); 
```

**Comment by medyas** [comment]
@alibasta have this solved your issue ?

**Comment by alibasta** [comment]
Hi @medyas It works like a charm now! Thank you very much! Sorry for responding late.
