### ISSUE TITLE
Best way to use this package!

### ISSUE THREAD

**Issue by watsmyname** [medyas/flutter_zoom_drawer#101]
Actually this is not the issue, but more like a question. I am pretty new to flutter, have just started a few days back, so please bear with me.. 

I have around 30 pages in my app.  
1. So do I have to use ZoomDrawer widget  in all 30 pages and define parameters in all of them? If so later if something needs to be changed, I have to change on all pages? Isn't there a way to define this package once, and use them in whichever page I want?
2. Do i have to define ZoomDrawerController on all 30 pages?
3. Do I need to dispose the ZoomDrawerController later? 

What is the best way to use this package on larger projects without impacting performance?

Thanks

**Comment by medyas** [comment]
@watsmyname the package acts like a drawer, so so you can wrap your main screen with it and switch between pages either using nested navigation or checking for selected page to display.
define your controller once, and use it across the app(use provider/GetIt or other packages).
no need to dispose it manually as it will be automatically de allocated.
