### ISSUE TITLE
Gradient background is not shown properly since 3.0.0 when zoomdrawer is open

### ISSUE THREAD

**Issue by timtimtim123** [medyas/flutter_zoom_drawer#103]
Hi there :)

Since i updated from` 2.3.1+1` to `3.0.2`, when i open the zoomdrawer it looks like this:
https://ibb.co/RbcDNGs

I dont know if the black background on the right half of the screen is an issue or a new function, but I dont found out how to stretch the gradientbackground over the hole screen.
Maybe with `drawerStyleBuilder`?😅

**Comment by medyas** [comment]
@timtimtim123 its a new feature. You can set the menu background color by using `menuBackgroundColor`
