### ISSUE TITLE
Opening the drawer after using material back button return assertion error

### ISSUE THREAD

**Issue by hantsaniala** [medyas/flutter_zoom_drawer#107]
When navigating to another page which have his own drawer and going back with the physical button, an animation error like the following was thrown:

```sh
_AssertionError ('package:flutter/src/animation/animation_controller.dart': Failed assertion: line 454 pos 7: '_ticker != null': AnimationController.forward() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.)
```
**NavBar_controller.dart**
```dart
class NavBarController extends GetxController {
  final zc = ZoomDrawerController();

  void toggleDrawer() {
    zc.toggle?.call(); // <!-- Error here
    update();
  }
}
```

**Comment by medyas** [comment]
@hantsaniala you called this method after disposing of the Drawer widget and your screen.
you should not call toggle after closing the screen.
if try to add checks in the method to verify that the widget is still mounted.
