### ISSUE TITLE
Ability to change selected highlight

### ISSUE THREAD

**Issue by Technorocker** [medyas/flutter_zoom_drawer#109]
Hello and thank you for this plugin, its such a great visual addition to my app. I'm not sure if its possible or not but I am using this with 5 or 6 menu pages and it works great so far. What I ran into is that I also use convexAppBottomBar plugin, and when I open the zoomdrawer and select a page to go to the selected page on menu gets highlighted as is should. but that page is nested in a similar  paging type system for the convexbottombar. So when I tap on of the other bottom bar tabs it goes to the new page. but when I open the zoomdrawer from that next page the highlight is still focused on the last page.

Is there a way to programmatically change the highlighted selection to reflect the new page I'm on?

**Comment by medyas** [comment]
@Technorocker the plugin does not keep the status of the selected item, this is managed by your implementation of the menu widget. So this is not related to the plugin.
