### ISSUE TITLE
Can't set gradient color as menuBackgroundColor 

### ISSUE THREAD

**Issue by Leekogram** [medyas/flutter_zoom_drawer#114]
Hello, Is there a way i can set gradient as the color of the menuBackgroundColor of the zoom drawer.. i am working with a mock up that requires me to do that.

**Comment by medyas** [comment]
deplicate #95 
this can be found in the example app code https://github.com/medyas/flutter_zoom_drawer/blob/6d9247610938e44e399780f58c55e1354add389d/example/lib/menu_page.dart#L34
