### ISSUE TITLE
Slide to open doesn't work when main screen has horizontal view pager

### ISSUE THREAD

**Issue by mingqlin** [medyas/flutter_zoom_drawer#115]
To reproduce, use example code part of this project:

https://raw.githubusercontent.com/medyas/flutter_zoom_drawer/master/example/lib/main.dart

user can't swipe to open zoom drawer from main screen, it appears TabBarView blocks the swipe event from reaching GestureDetector in Zoom Drawer

**Comment by 7Eltantawy** [comment]
@mingqlin have you get any solution for this?

**Comment by medyas** [comment]
@mingqlin you can have a menu button to toggle the drawer. 
The other solution is to disable the TabBar swipe gesture
