### ISSUE TITLE
Missing OnDrawerChangedListener | OnDrawerChangeFunction

### ISSUE THREAD

**Issue by HafizAnas145** [medyas/flutter_zoom_drawer#116]
There's No Listener To Check Whether The Drawer is Opened Or Not. I Tried To Add Custom Listener, But Couldn't Find A Way To Do It.

**Comment by medyas** [comment]
@HafizAnas145 you can use `ZoomDrawer.of(context).stateNotifier;` which is a `ValueNotifier` that emits the state of the Drawer(`DrawerState`).
Will be closing this issue.
