### ISSUE TITLE
Drawer closing animation lag? Not closing properly

### ISSUE THREAD

**Issue by KimVinod** [medyas/flutter_zoom_drawer#119]
I was previously using flutter 3.3.10 and your latest flutter_zoom_drawer 3.0.3
Everything was working perfectly fine until yesterday I decided to update flutter to 3.7.6
Also, I haven't changed code related to drawer.

Im using this:
```
final ZoomDrawerController z = ZoomDrawerController();
```
and onTap:
```
onTap: () {
	z.close!();
	Navigator.push(context, MaterialPageRoute(builder: (context) => const FavoritesScreen()));
},
```
Can you please look into it why the drawer stops in between and not closing fully until I come back to previous route.
I regret updating to latest version of flutter :(

https://user-images.githubusercontent.com/79586514/222886563-b4400d87-67b0-45d9-9e29-801924cafee3.mp4

**Comment by medyas** [comment]
@KimVinod after checking and debugging this, it looks like it caused by the framework and not the package.
The animation value is getting paused when you push a new route and then resumed.
The animation controller value stops between 0.1 & 0.3 then resume to 1. here is the output for the sample code:

```
// Click to push the new page 
I/flutter (28059): SlideValue: 0.0
I/flutter (28059): SlideValue: 0.266377
// Back button
I/flutter (28059): SlideValue: 1.0
```

Here is a sample code:

```dart

class TwoPanels extends StatefulWidget {

  const TwoPanels({Key? key,}) : super(key: key);

  @override
  _TwoPanelsState createState() => _TwoPanelsState();
}

class _TwoPanelsState extends State<TwoPanels> with TickerProviderStateMixin {
  late final AnimationController _controller = AnimationController(
    duration: const Duration(seconds: 2),
    vsync: this,
  )..addListener(() {
      print("SlideValue: ${_controller.value} - ${_controller.status}");
    });
  late final Animation<Offset> _offsetAnimation = Tween<Offset>(
    begin: Offset.zero,
    end: const Offset(1.5, 0.0),
  ).animate(CurvedAnimation(
    parent: _controller,
    curve: Curves.elasticIn,
  ));

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(
        title: const Text("Backdrop"),
        elevation: 0.0,
      ),
      body: Container(
        color: Colors.pink,
        child: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                "Back Panel",
                style: TextStyle(fontSize: 24.0, color: Colors.white),
              ),
              const SizedBox(
                height: 16,
              ),
              TextButton(
                onPressed: () {
                  if (_controller.status == AnimationStatus.completed) {
                    _controller.reverse();
                  } else {
                    _controller.forward();
                  }

                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => TestPage(),
                    ),
                  );
                },
                child: Text("Push"),
              ),
              const SizedBox(
                height: 16,
              ),
              SlideTransition(
                position: _offsetAnimation,
                child: const Padding(
                  padding: EdgeInsets.all(8.0),
                  child: FlutterLogo(size: 150.0),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class TestPage extends StatelessWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Text("Test Page !"),
      ),
    );
  }
}
```

**Comment by medyas** [comment]
@KimVinod I added a work around.
I updated the the `close/open/toggle` callbacks to return `TickerFuture?`  which will allow you to navigator to the next page after the animated has completed. So the drawer will close first, then you page will be displayed.
will push this change ASAP. 

```dart

  final navigator = Navigator.of(
    context,
  );
  z.close?.call()?.then(
        (value) => navigator.push(
          MaterialPageRoute(
            builder: (_) => TestPage(),
          ),
        ),
      );

```

**Comment by medyas** [comment]
> @KimVinod after checking and debugging this, it looks like it caused by the framework and not the package. The animation value is getting paused when you push a new route and then resumed. The animation controller value stops between 0.1 & 0.3 then resume to 1. here is the output for the sample code:
> 
> ```
> // Click to push the new page 
> I/flutter (28059): SlideValue: 0.0
> I/flutter (28059): SlideValue: 0.266377
> // Back button
> I/flutter (28059): SlideValue: 1.0
> ```
> 
> Here is a sample code:
> 
> ```dart
> class TwoPanels extends StatefulWidget {
> 
>   const TwoPanels({Key? key,}) : super(key: key);
> 
>   @override
>   _TwoPanelsState createState() => _TwoPanelsState();
> }
> 
> class _TwoPanelsState extends State<TwoPanels> with TickerProviderStateMixin {
>   late final AnimationController _controller = AnimationController(
>     duration: const Duration(seconds: 2),
>     vsync: this,
>   )..addListener(() {
>       print("SlideValue: ${_controller.value} - ${_controller.status}");
>     });
>   late final Animation<Offset> _offsetAnimation = Tween<Offset>(
>     begin: Offset.zero,
>     end: const Offset(1.5, 0.0),
>   ).animate(CurvedAnimation(
>     parent: _controller,
>     curve: Curves.elasticIn,
>   ));
> 
>   @override
>   void dispose() {
>     _controller.dispose();
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     final ThemeData theme = Theme.of(context);
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text("Backdrop"),
>         elevation: 0.0,
>       ),
>       body: Container(
>         color: Colors.pink,
>         child: Center(
>           child: Column(
>             mainAxisSize: MainAxisSize.min,
>             children: [
>               Text(
>                 "Back Panel",
>                 style: TextStyle(fontSize: 24.0, color: Colors.white),
>               ),
>               const SizedBox(
>                 height: 16,
>               ),
>               TextButton(
>                 onPressed: () {
>                   if (_controller.status == AnimationStatus.completed) {
>                     _controller.reverse();
>                   } else {
>                     _controller.forward();
>                   }
> 
>                   Navigator.push(
>                     context,
>                     MaterialPageRoute(
>                       builder: (_) => TestPage(),
>                     ),
>                   );
>                 },
>                 child: Text("Push"),
>               ),
>               const SizedBox(
>                 height: 16,
>               ),
>               SlideTransition(
>                 position: _offsetAnimation,
>                 child: const Padding(
>                   padding: EdgeInsets.all(8.0),
>                   child: FlutterLogo(size: 150.0),
>                 ),
>               ),
>             ],
>           ),
>         ),
>       ),
>     );
>   }
> }
> 
> class TestPage extends StatelessWidget {
>   const TestPage({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(),
>       body: Center(
>         child: Text("Test Page !"),
>       ),
>     );
>   }
> }
> ```

@KimVinod you can try to report the issue in the Flutter repo https://github.com/flutter/flutter/issues

**Comment by KimVinod** [comment]
> @KimVinod I added a work around. I updated the the `close/open/toggle` callbacks to return `TickerFuture?` which will allow you to navigator to the next page after the animated has completed. So the drawer will close first, then you page will be displayed. will push this change ASAP.
> 
> ```dart
>   final navigator = Navigator.of(
>     context,
>   );
>   z.close?.call()?.then(
>         (value) => navigator.push(
>           MaterialPageRoute(
>             builder: (_) => TestPage(),
>           ),
>         ),
>       );
> ```

ahh I see! Well thanks for the quick response! Looking forward to it 😇

**Comment by KimVinod** [comment]
@medyas If you could report, it would be nice as you are more knowledgeable than me! I'm still a newbie in these things haha
