### ISSUE TITLE
How to close the drawer after selecting the menu item?

### ISSUE THREAD

**Issue by zwchenlong** [medyas/flutter_zoom_drawer#12]
Dear Sir,

I tried to call ZoomDrawer.of(context).close() under the function assigned to menuScreen's callback, but I got the error showing I am calling a null function.

I also tried to call by using _drawerController.close(), but also got the same result.

May I know the solution on this?  Thank you.

**Comment by medyas** [comment]
@zwchenlong are you running the example app ? and did you pass the controller as :

```Dart
class _HomeScreenState extends State<HomeScreen> {
  final _drawerController = ZoomDrawerController();

  int _currentPage = 0;

  @override
  Widget build(BuildContext context) {
    return ZoomDrawer(
      controller: _drawerController,
      menuScreen: MenuScreen(
        HomeScreen.mainMenu,
        callback: _updatePage,
        current: _currentPage,
      ),
      mainScreen: MainScreen(),
      borderRadius: 24.0,
//      showShadow: true,
      angle: 0.0,
      slideWidth:
          MediaQuery.of(context).size.width * (ZoomDrawer.isRTL() ? .45 : 0.65),
      openCurve: Curves.fastOutSlowIn,
      closeCurve: Curves.bounceIn,
    );
  }

  void _updatePage(index) {
    Provider.of<MenuProvider>(context, listen: false).updateCurrentPage(index);
    _drawerController.toggle();
  }
}
```

**Comment by zwchenlong** [comment]
No, but I employed your sample code to my project and find that doesn't work.  Since the sample is working.  I'll take a further look to see what the problem is.  Thank you.
