### ISSUE TITLE
When I use DrawerStyle.style1 i can't open menu drawer

### ISSUE THREAD

**Issue by dragojsguru** [medyas/flutter_zoom_drawer#122]
ZoomDrawer(
      controller: _zDrwer,
      // openCurve: Curves.easeInOutCubic,
      // animateChildDecoration: true,
      // backdropColor: AppColors.bodyColor,
      // openRatio: 0.9,
      moveMenuScreen: false,
      mainScreenTapClose: true,
      disableDragGesture: false,
      slideWidth: MediaQuery.of(context).size.width * 0.9,
      overlayBlur: 10,
      duration: const Duration(milliseconds: 150),
      angle: 0,
      style: DrawerStyle.defaultStyle,
      menuScreen: MainDrawer(
        drawerController: _zDrwer,
        onPressed: () {},
      ),\

In situation when I use defaultStyle everything is working properly

**Comment by youssefibrahim146** [comment]
i used defult style but i still have the same problem the drawer open but its menu screen didnt apear and the drawer bug

**Comment by huzaifansari54** [comment]
hello can i work on this issue
