### ISSUE TITLE
_CastError (Null check operator used on a null value)

### ISSUE THREAD

**Issue by CarlloydViray** [medyas/flutter_zoom_drawer#123]
Whenever i register a new account from my registerScreen.dart, i navigate.push it to my authGate.dart that uses authChanges and returns homeScreen.dart with my zoomdrawer toggle in the appbar. But whenever i click on it, it shows a _CastError (Null check operator used on a null `value),` unless i perform a reload

**homeScreen.dart**
```
IconButton(
 onPressed: () {
 ZoomDrawer.of(context)!.toggle();
},
```
**registerScreen.dart**
```
Navigator.push(
        context,
        CupertinoPageRoute(
          builder: (context) {
            return authGate();
          },
        ),
      );
```

**authGate.screen**
```
StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return loginScreen();
          }
          return HomeScreen();
        });
```

**Comment by medyas** [comment]
try adding a controller or wrap your widget with a Builder
