### ISSUE TITLE
No constant background in the menu screen

### ISSUE THREAD

**Issue by tbspace** [medyas/flutter_zoom_drawer#126]
With the latest version of this package I got the issue that the background with the opened drawer isn't constant filled. Right beside the widget the screen is grey instead of the the LineaGradient Color. Additionally I get some visualizing issues with the SafeArea with the opened drawer.

When using the version 2.0.2+4 eveything is fine. See screenshots atached.

![ZoomDrawer_Issue](https://github.com/medyas/flutter_zoom_drawer/assets/49919542/d982c5ff-9b0f-4e62-8807-4d021324c3b2)
![ZoomDrawer_No-Issue](https://github.com/medyas/flutter_zoom_drawer/assets/49919542/0cee79d8-425c-40ec-9d53-ca6b48635da5)

**Comment by tbspace** [comment]
Update: The bug/issue came in version 3.0.0

**Comment by medyas** [comment]
@tbspace could you provide a sample example to reproduce the issue

**Comment by tbspace** [comment]
@medyas Sure, you can find attached 2 versions. One with the last working version without the bug and one with the latest package version containing the bug.

Let me know, if you need more information.

[ZoomDrawerExample_LastWorkingVersion.zip](https://github.com/medyas/flutter_zoom_drawer/files/11871874/ZoomDrawerExample_LastWorkingVersion.zip)
[ZoomDrawerExample_LatestVersionWIthIssue.zip](https://github.com/medyas/flutter_zoom_drawer/files/11871875/ZoomDrawerExample_LatestVersionWIthIssue.zip)

**Comment by medyas** [comment]
@tbspace to fix you issue, just pass `menuScreenWidth` to the `ZoomDrawer` widget and give it the full screen width.
```dart
menuScreenWidth: MediaQuery.of(context).size.width,
```
