### ISSUE TITLE
Error when reading `config.dart': No such file or directory

### ISSUE THREAD

**Issue by shreks7** [medyas/flutter_zoom_drawer#128]
I am getting this error building on iOS - 

```
Could not build the precompiled application for the device.
Error (Xcode): lib/controllers/common/drawer_controller.dart:2:8: Error: Error when reading '../../../../../.pub-cache/hosted/pub.dev/flutter_zoom_drawer-3.1.1/lib/config.dart': No such file or directory
```

Any ideas? Thank you.

**Comment by shreks7** [comment]
`flutter clean` fixed it

**Comment by malkabani** [comment]
Hello
I still have same issue even if I run
flutter clean

**Comment by basemkhirat** [comment]
still have error

**Comment by malkabani** [comment]
Try this it maybe fix the issue
`
flutter clean

remove ios/.symlinks and ios/Pods folders and ios/podfile.lock file

cd ios && pod deintegrate

flutter pub get

pod install

flutter run -v
`
