### ISSUE TITLE
Example using BloC pattern

### ISSUE THREAD

**Issue by devZakariya** [medyas/flutter_zoom_drawer#13]
Dear Sir,
Hello,
Thanks for this great flutter menu!

please how can  i integrate this package with the BloC pattern

**Comment by medyas** [comment]
Hi @devZakariya ,
Both Provider and BloC are state management packages, and it depends on the developers preference to implement what they like.
Based on the [BloC usage](https://pub.dev/packages/flutter_bloc#usage) you could use a `Cubit` and in it manage the current page index, then use it in the Widget tree and update the current page.

```Dart
class MenuCubit extends Cubit<int> {
  MenuCubit() : super(0);

  void updateCurrentPage(int index) {
    if (index != state) {
      state = index;
    }
  }
}
```

in HomeScreenState class :

```Dart
void _updatePage(index) {
    context.bloc<MenuCubit>().updateCurrentPage(index);
    _drawerController.toggle();
}
```

in PageStructure :

```Dart
  @override
  Widget build(BuildContext context) {
    final angle = ZoomDrawer.isRTL() ? 180 * pi / 180 : 0.0;
    final container = BlocBuilder<MenuCubit, int>(
        builder: (context, count) => Container(
      			color: Colors.grey[300],
      			child: Center(
        		child: Text(
            		"${tr("current")}: ${HomeScreen.mainMenu[count].title}"),
      				),
    			),
        	);

    ...
}
```

**Comment by devZakariya** [comment]
thank you a lot for the fast response
