### ISSUE TITLE
Can you provide a tutorial on how to use isOpen method.

### ISSUE THREAD

**Issue by mani53-dev** [medyas/flutter_zoom_drawer#133]
Can you provide a tutorial on how to use isOpen() method. It is giving the value after the build method and null before that. I wanna have some UI updation on main screen depending on if wethere the drawer is closed or opened

**Comment by medyas** [comment]
@mani53-dev you can use `ZoomDrawer.of(context).stateNotifier` to listen to the drawer state `DrawerState` changes and build your UI.

**Comment by mani53-dev** [comment]
Thanks, State Notifier works for me but it does not emit the state 'Closed' or 'Closing' when closing the drawer by sliding from the main screen.

**Comment by medyas** [comment]
@mani53-dev sorry for the delayed response.
I have tested the state notifier, and found that it does emit all the states.
could you provide an example project/code sample to reproduce the issue.
Thanks
