### ISSUE TITLE
OnBackpress, redirect to home page, 

### ISSUE THREAD

**Issue by MuhammadIbrahimSE** [medyas/flutter_zoom_drawer#134]
I want to return back to homepage from any selected page on backpress.
is there any existing way? how can i do that

**Comment by medyas** [comment]
@MuhammadIbrahimSE could you provide a sample project

**Comment by MuhammadIbrahimSE** [comment]
https://github.com/medyas/flutter_zoom_drawer/assets/27722011/bae48f02-8499-43b7-9417-f70580b8d3c6

on pressing profile it goes to profile, but from profile, on backpress it redirects back to home screen

**Comment by medyas** [comment]
Its unrelated to the package. You should update your navigation logic to support going back to home page.
