### ISSUE TITLE
popscop error

### ISSUE THREAD

**Issue by hina06botify** [medyas/flutter_zoom_drawer#137]
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...
../../../.pub-cache/hosted/pub.dev/flutter_zoom_drawer-3.2.0/lib/src/flutter_zoom_drawer.dart:824:22: Error: The method 'PopScope' isn't defined for the class 'ZoomDrawerState'.
 - 'ZoomDrawerState' is from 'package:flutter_zoom_drawer/src/flutter_zoom_drawer.dart' ('../../../.pub-cache/hosted/pub.dev/flutter_zoom_drawer-3.2.0/lib/src/flutter_zoom_drawer.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PopScope'.
      parentWidget = PopScope(
                     ^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/keval/Documents/development/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1297

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/keval/Documents/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by medyas** [comment]
@hina06botify you need to upgrade to the latest flutter sdk
