### ISSUE TITLE
Listen to the change of animation value

### ISSUE THREAD

**Issue by SageMik** [medyas/flutter_zoom_drawer#138]
Is there any way to listen to the change of animation value, since it is useful for linking other animations?
https://github.com/medyas/flutter_zoom_drawer/blob/e18faa1437ff63bb5d749519a3c5619d2964d5f5/lib/src/flutter_zoom_drawer.dart#L215-L221
Currently I can't find a way to do this, so I add `onAnimationValueChange` field for listening as below:
```
final void Function(double value)? onAnimationValueChange;
```
```
late final AnimationController _animationController = AnimationController(
    vsync: this,
    duration: widget.duration,
    reverseDuration: widget.duration,
  )..addStatusListener(_animationStatusListener)
   ..addListener(() => widget.onAnimationValueChange?.call(_animationValue));
```
Could you please make it a new feature?

**Comment by medyas** [comment]
@SageMik could you create a PR with these changes

**Comment by SageMik** [comment]
@medyas I have created #139.
