### ISSUE TITLE
Fix Incorrect Usage of PopScope in flutter_zoom_drawer which Causes Build Failures

### ISSUE THREAD

**Issue by sharopcha** [medyas/flutter_zoom_drawer#144]
Description:
There is a critical typo in the flutter_zoom_drawer.dart implementation where PopScope is used instead of WillPopScope. This typo causes build failures when attempting to run apps on Android devices, specifically throwing an error that PopScope isn't defined.

Error Encountered:
The following error is thrown during the build process:

`Error: The method 'PopScope' isn't defined for the class 'ZoomDrawerState'.
`

This error points to a line of code in flutter_zoom_drawer.dart where PopScope is mistakenly used.

Expected Behavior:
WillPopScope should be used to manage whether the drawer can be closed by Android's back button, ensuring that the navigation context handles back press events appropriately when the drawer is open.

Current Faulty Code:

`// Add layer - PopScope
if (!kIsWeb &&
    defaultTargetPlatform == TargetPlatform.android &&
    widget.androidCloseOnBackTap) {
  parentWidget = PopScope(
    canPop: _canPop(),
    child: parentWidget,
  );
}
`

Correct Implementation:
Replace PopScope with WillPopScope.
Ensure _canPop returns a Future<bool> and pass it correctly to onWillPop.
Corrected Code Snippet:

`// Correct method signature with async and proper return type
Future<bool> _canPop() async {
  if ([DrawerState.open, DrawerState.opening].contains(stateNotifier.value)) {
    close(); // Assuming close() method handles closing logic
    return Future.value(false);
  }
  return Future.value(true);
}
// Add layer - WillPopScope
if (!kIsWeb &&
    defaultTargetPlatform == TargetPlatform.android &&
    widget.androidCloseOnBackTap) {
  parentWidget = WillPopScope(
    onWillPop: _canPop,  // Pass reference to the function
    child: parentWidget,
  );
}
`

Steps to Reproduce:
Use flutter_zoom_drawer in a Flutter project.
Attempt to run the application on an Android device.
Observe the build failure with a reference to PopScope not being defined.
Impact:
This issue prevents successful builds on Android devices and potentially affects all users utilizing the flutter_zoom_drawer with back button handling enabled.

Proposed Solution:
The above corrections should be integrated into the next release of the flutter_zoom_drawer package. This would resolve the build errors and align the implementation with Flutter's expected behavior for handling back navigation with WillPopScope.

**Comment by medyas** [comment]
@sharopcha Thanks for the description.
Unfortunately, its not a faulty code, `WillPopScope` widget was [deprecated](https://docs.flutter.dev/release/breaking-changes/android-predictive-back) in favor of `PopScope` and so the package has migrated.
You should upgrade your Flutter SDK to the latest too be able to use the latest version of the package. Or you could force use [V3.1.2](https://github.com/medyas/flutter_zoom_drawer/commit/31eba1e99a8ed76669d9f722d572f7ecd25b2cc2) of the package which is before the migration.
Thanks!
