### ISSUE TITLE
Null stateNotifier on ZoomController

### ISSUE THREAD

**Issue by ElZombieIsra** [medyas/flutter_zoom_drawer#15]
Hi.

I was using this package and I was trying to use one of the latests features that its the `stateNotifier` in the `ZoomController` but I got the error `The getter 'value' was called on null.`

This is a sample class that should demonstrate the error

```dart
class MyDrawer extends StatelessWidget {
  final ZoomDrawerController _controller = ZoomDrawerController();
  final Widget content;

  MyDrawer({
    Key key,
    @required this.content,
  })  : assert(content != null),
        super(key: key);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ZoomDrawer(
        controller: _controller,
        angle: 0.0,
        showShadow: true,
        menuScreen: Container(),
        mainScreen: GestureDetector(
          onTap: () {
            print('test');
          },
          child: AbsorbPointer(

            /// Here the app crashes because stateNotifier is [null]. 
            /// I could wrap it in a null safety operator but I really need to access the notifier to get the value.
            absorbing: _controller.stateNotifier.value == DrawerState.closed,  
            child: content,
          ),
        ),
      ),
    );
  }
}
```

The question is: 
Am I using wrong the `ZoomController` or its a package wide problem?

**Comment by medyas** [comment]
@ElZombieIsra sorry for the late response.
Your trying to access the controller before its initialized.
Try putting your `AbsorbPointer `widget inside a `Builder `or in an Stateless widget and use `ZoomDrawer.of(context)` to access the `stateNotifier`
