### ISSUE TITLE
Facing issue with RTL support

### ISSUE THREAD

**Issue by chauhanumesh** [medyas/flutter_zoom_drawer#18]
I had run the example code with only Arabic locale but the drawer menu doesn't toggle as expected
Please refer image for further clarification.

![1606245173722](https://user-images.githubusercontent.com/63291590/100141360-50d61680-2eb8-11eb-928a-d3571b51f6ff.JPEG)

**Comment by medyas** [comment]
@chauhanumesh you app in Arabic language but the system language is not Arabic. The drawer RTL/LTR support is based on the system language and not the app. you need to change the system language for the RTL support to work.

**Comment by chauhanumesh** [comment]
ok, Got it.
Thanks for the quick reply :)
