### ISSUE TITLE
[Bug] Drawer state is disposed before controller is disposed

### ISSUE THREAD

**Issue by aria-grande** [medyas/flutter_zoom_drawer#19]
Hi, thanks for making awesome library.

# Issue
By the way, I am getting exceptions as below.
![Screen Shot 2020-11-26 at 9 40 55 PM](https://user-images.githubusercontent.com/16955811/100415165-59515d00-3030-11eb-9fe3-2c6636263ba5.png)

# Suggestion
animationController should be disposed before super.dispose. Otherwise, the state is disposed before the animation controller and ticker will leak

```dart

  @override
  void dispose() {
    _animationController.dispose();
    super.dispose();
  }
```

Tried to contribute, but creating a branch from my cloned repo is not working, so I am creating an issue instead.

Thanks

**Comment by medyas** [comment]
Hello, thanks for the suggestion.
I have published a new version with the fix [1.0.4+1]
