### ISSUE TITLE
Using with Scaffold ?

### ISSUE THREAD

**Issue by vptcnt** [medyas/flutter_zoom_drawer#2]
Hello,

The design is awesome. 
Is it possible to use it with a scaffold ? I am newbie in Flutter.
Thanks for your help

Vincent

**Comment by medyas** [comment]
Hi,
The package wrap around two screens, and it's up to you to put what ever widget you want. Here is a snippet from the example:
```dart

return ZoomDrawer(
      controller: _drawerController,
      menuScreen: MenuScreen(
        HomeScreen.mainMenu,
        callback: _updatePage,
        current: _currentPage,
      ),
      mainScreen: MainScreen(),
      borderRadius: 24.0,
      showShadow: true,
      angle: -12.0,
      slideWidth:
          MediaQuery.of(context).size.width * (ZoomDrawer.isRTL() ? .45 : 0.65),
    );
```

Your `mainScreen` can be a `Scaffold` with your page inside.
In the example i user `PageStructure `which is a widget with support for both Android and iOS (shows `Scaffold `on Android and `CupertinoScaffold `in iOS)
