### ISSUE TITLE
Add option to chance scale of main screen

### ISSUE THREAD

**Issue by rvdsoft** [medyas/flutter_zoom_drawer#25]
At the moment the scale of the main screen (when drawer is open) is a fixed percentage that can't be changed. 
For each style (with some exceptions) `0.3` is used as fixed scale percentage:
```dart
double scale = 1 - (_animationController.value * 0.3);
```
This fixed value could be replaced with a widget attribute to make it part of the public API:
```dart
double scale = 1 - (_animationController.value * widget.mainScreenScale);
```

**Comment by medyas** [comment]
@rvdsoft you can submit a pull  request, and will be happy to merge

**Comment by LebToki** [comment]
How do you trigger mainScreenScale then ?

> @rvdsoft you can submit a pull request, and will be happy to merge
