### ISSUE TITLE
I can't scroll the screen

### ISSUE THREAD

**Issue by dmrcierhn** [medyas/flutter_zoom_drawer#27]
I'm trying to use a webview on the home screen, but when I want to scroll up, the menu opens. and I can't use webview. how can i fix this? thank you

**Comment by medyas** [comment]
you will have to disable the swipe gesture on the menu, which is currently not implemented.
you could submit a pull request with the fix or wait for me to add this(will try to see if i could do it this weekend).

**Comment by dmrcierhn** [comment]
How can I disable the swipe gesture?

**Comment by medyas** [comment]
you will have to edit the package source

**Comment by dmrcierhn** [comment]
which code block should I check?

**Comment by develogo** [comment]
The same happens with maps

**Comment by develogo** [comment]
@dmrcierhn you can fork this repo and edit lib/flutter_zoom_drawer.dart  line 261.

Replace 
@override
  Widget build(BuildContext context) {
    return GestureDetector(
      /// Detecting the slide amount to close the drawer in RTL & LTR
      onPanUpdate: (details) {
        if (_state == DrawerState.open && details.delta.dx < -6 && !_rtl ||
            details.delta.dx < 6 && _rtl) {
          toggle();
        }
      },
      child: renderLayout(),
    );
  }

FOR

 @override
  Widget build(BuildContext context) {
    return renderLayout();
 }

Commit and push.  Go to you pubspec.yaml project file and change:
dependencies:
  flutter_zoom_drawer: 
    git:
      url: you link repo forked

**Comment by medyas** [comment]
I have added a new parameter `disableGesture` which allows you to disable the swipe gesture on the home page
