### ISSUE TITLE
Is very slow in release build, we need 60 fps

### ISSUE THREAD

**Issue by SaylaRdota** [medyas/flutter_zoom_drawer#29]

**Comment by medyas** [comment]
can you share your app ? and how are you testing the fps ?

**Comment by SaylaRdota** [comment]
Are you testing the Drawer Sliding with rotation and shadows in release?. In my case in release is not fluid. My phone is Android Xiaomi note 8 pro, 6 ram, 8 cores.

**Comment by alejandrogiubel** [comment]
Same here. In fisics devices the animation is not totaly fluid.

**Comment by medyas** [comment]
maybe you rendering alot of widgets in the home screen which causes performance issues ?
can you share you code ?

**Comment by medyas** [comment]
@SaylaRdota  ?

**Comment by medyas** [comment]
closing as there is no response.
