### ISSUE TITLE
Add ability to know if the drawer is opened or closed

### ISSUE THREAD

**Issue by ElZombieIsra** [medyas/flutter_zoom_drawer#3]
I'm currently working with this plugin (pretty great, btw) but I see is lacking the ability to know if the drawer is opened or closed.
I think this is a very important feature to this plugin.
I guess this could be implemented in the ZoomDrawerController. 

When I have a little more free time I can work on this if you can't

**Comment by medyas** [comment]
Thank you for the feedback, and will add this in the next 48h

**Comment by medyas** [comment]
Quick question, will rather two booleans isOpen and isClosed or a drawer status enum ?

**Comment by ElZombieIsra** [comment]
I was thinking a boolean in the ZoomDrawerController called isOpen. That seems enough. What do you think?

**Comment by medyas** [comment]
Yeah, that's fine with me. Will work on it today.

**Comment by medyas** [comment]
Have added :
```
_drawerController.isOpen();
ZoomDrawer.of(context).isOpen();
```

which will return a `bool` whether the drawer is fully open or not.
[flutter_zoom_drawer](https://pub.dev/packages/flutter_zoom_drawer/versions/1.0.2)

will close this issue, i have an issue with the implementation of the feature open it again.
