### ISSUE TITLE
when I change the localization to arabic RTL does not work as shown in the figure bellow ? 

### ISSUE THREAD

**Issue by YaseenSaif** [medyas/flutter_zoom_drawer#30]
![aaa](https://user-images.githubusercontent.com/52496812/111588384-89399180-87d4-11eb-8efd-8a4e0686ec6b.PNG)

**Comment by medyas** [comment]
can you provide a snippet of your code

**Comment by YaseenSaif** [comment]
I have downloaded the provided example and tried it in the emulator directly ,I did not change any thing yet ..what is the problem do u think?

**Comment by medyas** [comment]
ok, will try to check it in the weekend and get back to you

**Comment by YaseenSaif** [comment]
thanks a lot

**Comment by medyas** [comment]
fixed in latest release
