### ISSUE TITLE
Properties like borderRadius, showShadow, angle no longer work

### ISSUE THREAD

**Issue by fede1295** [medyas/flutter_zoom_drawer#33]
Reproduced with different versions of module, flutter and dart but it doesn't work anymore in any way...

on Nov 27, 2020
https://github.com/medyas/flutter_zoom_drawer/blob/fc50763049bff751449c8225fef92d9286779c1b/lib/flutter_zoom_drawer.dart 

this bug was not there.. please fix it

**Comment by medyas** [comment]
ok will work on it

**Comment by medyas** [comment]
`showShaow` and `angle` are only available in `DrawerStyle.Style1`
I added borderRadius to supported styles
