### ISSUE TITLE
behavior at start up

### ISSUE THREAD

**Issue by nholmvio** [medyas/flutter_zoom_drawer#37]
Hi...thanks for your work on this package.

I'm noticing on startup of my app, the Drawer contents are being shown for a brief second before the actual main screen gets rendered, rather than drawing the main screen (and keeping drawer hidden)

I'm sure i'm just doing something wrong here in my implementation.   Does anyone have any suggestion on where i may be going wrong that causes this behavior?

Thanks

**Comment by medyas** [comment]
can you share an example to reproduce the issue ?

**Comment by nholmvio** [comment]
Thanks for the quick response!  

I don't have a small standalone (I may need to do that).   

I don't think i'm doing anything unique, and trying to follow example...  Any thing this sparks idea to try? 

Thanks so much.

```
   return ViewModelBuilder<ClientHomeViewModel>.reactive(
      builder: (context, model, child) {
        return !model.modelReady
            ? Container(color: Colors.red)   //temp debugging
            : ZoomDrawer(
                controller: _drawerController,
                style: DrawerStyle.DefaultStyle,
                menuScreen: _buildDrawer(model),
                mainScreen: _buildMain(model),
                angle: 0.0,
                backgroundColor: Colors.grey[300],
                slideWidth: MediaQuery.of(context).size.width *
                    (ZoomDrawer.isRTL() ? .45 : 0.65),
              );
      },
      viewModelBuilder: () => locator<ClientHomeViewModel>(),
    );

```

**Comment by nholmvio** [comment]
Ah....i found it, i had a slight fade delay buried down  in the main screen build causing that slight visibility of the drawer!

Thanks again for quick replies and the nice work on this package.
