### ISSUE TITLE
'Locale' is from 'dart:ui'

### ISSUE THREAD

**Issue by mustafa-fahimi** [medyas/flutter_zoom_drawer#38]
Hi. I have this issue when running on the web with null-safety

flutter_zoom_drawer-2.0.1/lib/flutter_zoom_drawer.dart:106:38: Error: Property 'languageCode' cannot be accessed on 'Locale?' because it is potentially null.
 - 'Locale' is from 'dart:ui'.
Try accessing using ?. instead.
    String locale = ui.window.locale.languageCode.toLowerCase();
                                     ^^^^^^^^^^^^

**Comment by medyas** [comment]
hello, this has been fixed in the latest version
