### ISSUE TITLE
String? locale = ui.window.locale?.languageCode?.toLowerCase();

### ISSUE THREAD

**Issue by mustafa-fahimi** [medyas/flutter_zoom_drawer#40]
You fixed the null-safety error for locale but another error created. Please fix this too.

flutter_zoom_drawer-2.0.2/lib/flutter_zoom_drawer.dart:106:32: Warning: Operand of null-aware operation '?.' has type 'Locale' which excludes null.
 - 'Locale' is from 'dart:ui'.
    String? locale = ui.window.locale?.languageCode?.toLowerCase();

I suggest use this:
String? locale = ui.window.locale.languageCode!.toLowerCase();
or this:
String? locale = ui.window.locale!.languageCode.toLowerCase();

**Comment by medyas** [comment]
the message your getting is a warning and not an error.

**Comment by zneti-sourour** [comment]
I didn't understand how to solve this warning. where i can put this :  String? locale = ui.window.locale.languageCode!.toLowerCase();
