### ISSUE TITLE
all is working fine. But i have this warning

### ISSUE THREAD

**Issue by zneti-sourour** [medyas/flutter_zoom_drawer#42]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_drawer-2.0.2+1/lib/flutter_zoom_drawer.dart:106:30: Warning: Operand of null-aware operation '!' has type 'Locale' which excludes null.
 - 'Locale' is from 'dart:ui'.
    final locale = ui.window.locale!.languageCode.toLowerCase();

**Comment by medyas** [comment]
@zneti-sourour this is just a warning, will not cause any issue

**Comment by oguzhan2142** [comment]
same warning

../../Frameworks/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_drawer-2.0.2+1/lib/flutter_zoom_drawer.dart:106:30: Warning: Operand of null-aware operation '!' has type 'Locale' which excludes null.
 - 'Locale' is from 'dart:ui'.
    final locale = ui.window.locale!.languageCode.toLowerCase();
                             ^

**Comment by ZaifSenpai** [comment]
same

**Comment by medyas** [comment]
fixed in latest version

**Comment by devrajraut** [comment]
> fixed in latest version

I still have this Error in the Latest Version 2.0.2+4
