### ISSUE TITLE
Add shadow to MainScreen

### ISSUE THREAD

**Issue by ZaifSenpai** [medyas/flutter_zoom_drawer#43]
How can we show the shadow of MainScreen to the background below?

![image](https://user-images.githubusercontent.com/16265942/119133944-f2988380-ba55-11eb-8ced-fa819d39526d.png)

**Comment by medyas** [comment]
did not understand, can you explain your issue

**Comment by ZaifSenpai** [comment]
This is showing a drawer open. The MainScreen on the Left does not have any shadow. What I am trying to do is to give a shadow to the MainScreen (something like on the right)

![image](https://user-images.githubusercontent.com/16265942/119191114-aa9a5080-ba97-11eb-8d6b-513582306bd3.png)

**Comment by ZaifSenpai** [comment]
This is showing a drawer open. The MainScreen on the Left does not have any shadow. What I am trying to do is to give a shadow to the MainScreen (something like on the right)

![image](https://user-images.githubusercontent.com/16265942/119191420-095fca00-ba98-11eb-8e80-62d58b999843.png)

**Comment by medyas** [comment]
then just wrap your mainscreen with a container and add shadow to it, that should give you what you want.
this is not related to the plugin it self so will close it

**Comment by ZaifSenpai** [comment]
of course, I have already tried it. I do not want the shadow inside the MainScreen, I want it outside of it. If I add padding to MainScreen and add shadow to show it, this drawer widget will cut off the shadow (clip) and show a square.

**Comment by medyas** [comment]
you can set the borderRadius parameter to 0.0 . by this, mainscreen won't be clipped

**Comment by ZaifSenpai** [comment]
![image](https://user-images.githubusercontent.com/16265942/119192689-f817bd00-ba99-11eb-8d50-c3dae71f4870.png)

**Comment by medyas** [comment]
@ZaifSenpai working on a fix right now

**Comment by medyas** [comment]
added a bool parameter clipMainScreen, set it to false and it will show mainscreen without clipping.
`flutter_zoom_drawer: ^2.0.2+3`

**Comment by ZaifSenpai** [comment]
@medyas Thank you! It worked:
![image](https://user-images.githubusercontent.com/16265942/119206489-bba58a80-bab4-11eb-856b-23fea36e803e.png)
