### ISSUE TITLE
Library can't build for web app

### ISSUE THREAD

**Issue by nguyenlinhnttu** [medyas/flutter_zoom_drawer#46]
Hi Medyas, thanks for your library, i have problem when run web app, please help me have a look.

`💪 Building with sound null safety 💪

Target dart2js failed: Exception: ../../FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_drawer-2.0.2+3/lib/flutter_zoom_drawer.dart:117:31:
Error: Property 'languageCode' cannot be accessed on 'Locale?' because it is potentially null.
 - 'Locale' is from 'dart:ui'.
      return ui.window.locale.languageCode.toLowerCase();
                              ^^^^^^^^^^^^
Error: Compilation failed.
`

flutter doctor.
`[✓] Flutter (Channel stable, 2.0.3, on macOS 11.0.1 20B50 darwin-x64, locale en-VN)
    • Flutter version 2.0.3 at /Users/NguyenLinh/FlutterSDK/flutter
    • Framework revision 4d7946a68d (3 months ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/NguyenLinh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/NguyenLinh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.0.1 20B50 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.
Process finished with exit code 0`

**Comment by medyas** [comment]
fixed in latest version
