### ISSUE TITLE
Style 1 drag menu jittering

### ISSUE THREAD

**Issue by MichalNemec** [medyas/flutter_zoom_drawer#48]
Hello, in your example if i set style1 and try to just drag and hold the menu button to show the drawer, its jittering and all over the place.

Could you do something with that? and also on Flutter 2 it yells about the same thing still which is in issue #47

**Comment by medyas** [comment]
can you provide  more details about the issue? does not occur in my test. Could you share a video or some code

**Comment by MichalNemec** [comment]
i downloaded your whole project and just ran example you have there.
Changed DrawerStyle to Style1.
then keep holding the menu icon and move left and right like crazy person and it then goes all over the place. 
Another visual stuff is when the menu is opened and going back to full screen view, its not smooth.

Could it be that im running it inside android emulator?

**Comment by medyas** [comment]
to test the performance you will have to run the app in release mode and in a real device, not an emulator
