### ISSUE TITLE
Failed assertion: boolean expression must not be null [Flutter Web]

### ISSUE THREAD

**Issue by sarvex** [medyas/flutter_zoom_drawer#5]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building MenuScreen(dirty, state: _MenuScreenState#2bbc9):
Failed assertion: boolean expression must not be null

The relevant error-causing widget was: 
  MenuScreen file:/drawer/home_page.dart:36:19
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 195:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 419:40  _throwBooleanConversionError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 410:50  test
packages/toffeecover/page/drawer/menu_page.dart 34:11                             build
packages/flutter/src/widgets/framework.dart 4619:28                               build
...
════════════════════════════════════════════════════════════════════════════════════════════════════

The Drawer work perfectly on the mobile, however when running the code in flutter web, a red screen shows up with following exception

**Comment by medyas** [comment]
**Updated**
After running the web version, i found out that this is not related to the package it self but to the example. There are couple of calls to `Platform.isAndroid/Platform.isIos` which are causing this error.
To fix this, just test for web support first:

`import 'package:flutter/foundation.dart' show kIsWeb;`
`MenuPage`: `final style = kIsWeb? androidStyle : Platform.isAndroid? androidStyle: iosStyle;`

![zoom_web](https://user-images.githubusercontent.com/13151636/80380799-fa5c1780-8897-11ea-8e43-fb2dfb6cad80.PNG)

Here is the full running example: 
[zoom_web.zip](https://github.com/medyas/flutter_zoom_drawer/files/4540075/zoom_web.zip)

**Comment by sarvex** [comment]
Thanks a lot. Will check and report back
