### ISSUE TITLE
Swipe up Drawer opens 

### ISSUE THREAD

**Issue by arunkarthika** [medyas/flutter_zoom_drawer#50]
When we swipe up or down the drawer opens automatically.pls help me

**Comment by medyas** [comment]
can you share your code

**Comment by arunkarthika** [comment]
return ZoomDrawer(
      controller: _drawerController,
      style: DrawerStyle.Style1,
      menuScreen: MenuScreen(
        HomeScreen.mainMenu,
        callback: _updatePage,
        current: _currentPage,
      ),
      mainScreen: MainScreen(),
      borderRadius: 24.0,
     showShadow: true,
      angle: 0.0,
      mainScreenScale: .1,
      slideWidth: MediaQuery.of(context).size.width * (isRtl ? .55 : 0.65),
      isRtl: isRtl,
      clipMainScreen: true,
      disableGesture: false,

      // openCurve: Curves.fastOutSlowIn,
      // closeCurve: Curves.bounceIn,
    );

**Comment by medyas** [comment]
you can disable the swipe gesture and this will fix the issue

**Comment by arunkarthika** [comment]
I tried also I got the same issue bro

**Comment by arunkarthika** [comment]
return ZoomDrawer(
  controller: _drawerController,
  style: DrawerStyle.Style1,
  menuScreen: MenuScreen(
    HomeScreen.mainMenu,
    callback: _updatePage,
    current: _currentPage,
  ),
  mainScreen: MainScreen(),
  borderRadius: 24.0,
 showShadow: true,
  angle: 0.0,
  mainScreenScale: .1,
  slideWidth: MediaQuery.of(context).size.width * (isRtl ? .55 : 0.65),
  isRtl: isRtl,
  clipMainScreen: true,
  disableGesture: true,

  // openCurve: Curves.fastOutSlowIn,
  // closeCurve: Curves.bounceIn,
);

**Comment by arunkarthika** [comment]
How to disable swipe gesture bro

**Comment by medyas** [comment]
well setting the disabled attribute to `true` shoulde disable all the gesture in the package. Are you implementing a custom logic ?

**Comment by arunkarthika** [comment]
yes bro

**Comment by medyas** [comment]
@arunkarthika  yes for custom logic ?
