### ISSUE TITLE
Why I have error with "isRTL()" in "slideWidth: MediaQuery.of(context).size.width * (ZoomDrawer.isRTL() ? .45 : 0.65),"

### ISSUE THREAD

**Issue by TrongTam29** [medyas/flutter_zoom_drawer#52]
import 'package:flutter/material.dart';
import 'package:flutter_zoom_drawer/flutter_zoom_drawer.dart';
import 'package:my_app/screens/home%20screen/home_screen.dart';
import 'package:my_app/screens/menu%20profile/menu_profile.dart';

class HomeScreen extends StatefulWidget {
  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  final _drawerController = ZoomDrawerController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ZoomDrawer(
        controller: _drawerController,
        style: DrawerStyle.Style1,
        menuScreen: MenuProfile(),
        mainScreen: Home(_drawerController),
        borderRadius: 24.0,
        showShadow: true,
        angle: 0.0,
        backgroundColor: Colors.grey,
        slideWidth:
          MediaQuery.of(context).size.width * (ZoomDrawer.isRTL() ? .45 : 0.65),
        openCurve: Curves.fastOutSlowIn,
        closeCurve: Curves.bounceIn,
      ),
    );
  }
}

**Comment by TrongTam29** [comment]
The method 'isRTL' isn't defined for the type 'ZoomDrawer'.
Try correcting the name to the name of an existing method, or defining a method named 'isRTL'.

**Comment by medyas** [comment]
The `isRtl` method is no longer available in the latest version of the package, you should develop your own method for checking the RTL direction.

**Comment by YouSour** [comment]
@medyas i don't know how to check the RTL Direction , can you show me how can i do it ?

**Comment by medyas** [comment]
@YouSour well this will depend on what you use in ur app. To check with the current system language you can check the old implementation of `isRtl` https://github.com/medyas/flutter_zoom_drawer/blob/ae2c642e1da73ae96ff877ed86696ee84d1fa5a8/example/lib/main.dart#L52
