### ISSUE TITLE
Issue with the package?

### ISSUE THREAD

**Issue by nakshatrasinghh** [medyas/flutter_zoom_drawer#53]
Am I doing it correctly?

<img width="1440" alt="Screenshot 2021-08-31 at 10 15 21 PM" src="https://user-images.githubusercontent.com/53419293/131543185-8f012b6a-2367-4aab-ae75-2a308cfc7bd8.png">

Main Screen is returning a scaffold with appbar and Menu Screen is also returning a scaffold with appbar.

P.S. I am using MacBook Air M1

**Comment by medyas** [comment]
wrap the `ZoomDrawer` widget with `MaterialApp` widget

**Comment by nakshatrasinghh** [comment]
Yes, it works now. I'll close the issue now.
