### ISSUE TITLE
landscape mode have area error overflow

### ISSUE THREAD

**Issue by YouSour** [medyas/flutter_zoom_drawer#54]
hi , i just implement this package on project everything works fine , but it has a small problem on **_landscape mode have area error overflow_** like picture below , i try to wrap it with **SingleChildScrollView** but it still doesn't work , how can i fix this problem ? 
thank in advance
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-09-03 at 16 17 41](https://user-images.githubusercontent.com/9318106/131982366-f2fb86c6-b260-464f-b104-b647412310a9.png)

**Comment by medyas** [comment]
can you share a sample project ?

**Comment by YouSour** [comment]
@medyas i'm using `flutter_zoom_drawer: ^1.0.5` my  implement just same as example app , i think example app it also has this error on landscape mode. here simple project [https://github.com/YouSour/project-1](https://github.com/YouSour/project-1)

**Comment by medyas** [comment]
Can you try upgrading to the latest version and test again

**Comment by YouSour** [comment]
@medyas i just need scrollable on landscape , bro , i don't know where should i wrap with SingleChildScrollView

**Comment by medyas** [comment]
ok, will try to test the latest version in landscape and get back to you

**Comment by YouSour** [comment]
@medyas noted

**Comment by medyas** [comment]
hello @YouSour , you can wrap [Column](https://github.com/YouSour/project-1/blob/fb79b4cfc3220b1e77eca19185d24559fa53d1ca/lib/drawer.dart#L54) widget with `SingleChildScrollView` and just remove the `Spacer` widgets from the `Column`. You have 3 spacers, remove them and it should work.
PS: I tested this in the example app, and by wrapping the Column widget with SingleChildScrollView and removing all the Spacers the menu was scrolling as expected.

**Comment by YouSour** [comment]
@medyas thank you so much
