### ISSUE TITLE
Style1 has some kind of glitch when closing direction RTL

### ISSUE THREAD

**Issue by Amr1440** [medyas/flutter_zoom_drawer#55]
When closing drawer using Style1 it shows weird transition 

https://user-images.githubusercontent.com/52917852/132682351-2e6c805a-a259-45ef-9c6b-ca8f77b0075e.mp4

**Comment by medyas** [comment]
can you share the config your using for the ZoomDrawer

**Comment by Amr1440** [comment]
return ZoomDrawer(
      isRtl: true,
      controller: _drawerController,
      menuScreen: MenuScreen(),
      mainScreen: MainScreen(zoomDrawerController: _drawerController),
      borderRadius: 24.0,
      backgroundColor: Colors.grey[300],
      showShadow: true,
      angle: 0.0,
      slideWidth: MediaQuery.of(context).size.width * .65,
      openCurve: Curves.fastOutSlowIn,
      closeCurve: Curves.bounceIn,
      style: DrawerStyle.Style1,
    );

**Comment by medyas** [comment]
remove the closeCurve, as your setting it to bounceIn. Either remove it or set an other curve

**Comment by Amr1440** [comment]
thanks alot @medyas
