### ISSUE TITLE
DrawerStyle.Style3 animation artifact

### ISSUE THREAD

**Issue by Wentris71** [medyas/flutter_zoom_drawer#56]
hi, I encountered next issue, using `DrawerStyle.Style3`.

on captured video there are two Style modes, but the problem is obvious with first one.

Tested on IOS(14+) Iphone 12 pro,  and `platform :ios, '12.0'`

https://user-images.githubusercontent.com/18560311/133117501-a513b006-6f12-4c54-9eb3-280218e678ff.mov

**Comment by medyas** [comment]
@Wentris71 sorry for the late response. Unfortunately i dont't have access to a mac to test but this is related to Style3 effect as it offsets the menu page to outside the screen then translate it as needed and with the ios navigation transition does a swipe it is seen as an issue. To overcome this, i suggest to use a different style, as this is the desired effect by the style it just gets in conflict with the pages transitions
