### ISSUE TITLE
Flutter_zoom_drawerand MaterialRoute navigation

### ISSUE THREAD

**Issue by RoyalCoder88** [medyas/flutter_zoom_drawer#57]
How to use flutter_zoom_drawer with MaterialRoute for navigation to other screens? I tried but unsuccessfully :(
It's possible, can you guys provide an example? Thanks in advance!

**Comment by medyas** [comment]
you can do this using Nested Routes 
https://flutter.dev/docs/cookbook/effects/nested-nav
https://stackoverflow.com/questions/48098085/nesting-routes-with-flutter
