### ISSUE TITLE
I faced issue when I change app language from ar to en and back

### ISSUE THREAD

**Issue by yazeed-mohammad** [medyas/flutter_zoom_drawer#59]
Salam.

thanks for this wonderful library.

I faced issue when I change app language from English to Arabic or when change from Arabic to English.
the problem is menu screen not change direction and language until restart the app ,look at attachments please.

.
.

![Screenshot_1634419902](https://user-images.githubusercontent.com/35382725/137602658-f8fca096-1ff9-4c3d-97ad-6d44dc28316e.png)
![Screenshot_1634419793](https://user-images.githubusercontent.com/35382725/137602662-b718c87e-5c5d-41c5-b5b5-bceeba51687a.png)

**Comment by medyas** [comment]
you need to rebuild the drawer and pass it `isRtl` parameter to refresh its layout

**Comment by medyas** [comment]
could you provide sample code

**Comment by yazeed-mohammad** [comment]
when I rebuild layout, work fine.
thank you very much bro <3
