### ISSUE TITLE
I can't use this pachage ... 

### ISSUE THREAD

**Issue by Activecode001** [medyas/flutter_zoom_drawer#6]
sorry,
i'm new in flutter
but i will use this package
can you put full example to explain it
The design is awesome.
thank you for help

**Comment by medyas** [comment]
@Activecode001 The full example is already available under `example`:[Example app]( https://github.com/medyas/flutter_zoom_drawer/tree/master/example)

**Comment by Activecode001** [comment]
thank you
but i can't use it by provider
can use it without provider?

**Comment by medyas** [comment]
yes you can: [Link](https://github.com/medyas/flutter_zoom_drawer/issues/1#issuecomment-610387440)
