### ISSUE TITLE
There is no valid example

### ISSUE THREAD

**Issue by titoworlddev** [medyas/flutter_zoom_drawer#60]
The examples in the pub.dev readme page are very general and not fully understood and also in the example page the example that is posted is about another package called easy_localization, could you put it right?

**Comment by medyas** [comment]
can you explain your issue more ? like whats your problem ?

**Comment by titoworlddev** [comment]
Do I really have to explain it more? I have already said that there is no valid example, the example here
![Captura de pantalla de 2021-10-19 06-03-52](https://user-images.githubusercontent.com/70041483/137842473-ed6e066c-158e-45f7-8957-9437f5907b86.png)
it is about another package and does not refer to it.

And here in the readme section 
![Captura de pantalla de 2021-10-19 06-09-06](https://user-images.githubusercontent.com/70041483/137842591-c10c5115-c711-4b7a-9e72-d6384efbb160.png)
are valid but very generic examples where it does not even explain how to use them simply copy and paste, it is worse than looking in stackoverflow...

Likewise, I have already managed to use the package well, but if I had to have been guided by the explanation that is in pubdev I am sure that I would not have succeeded. And I don't know why @vanyasem disliked my comment for telling the truth.

**Comment by medyas** [comment]
The example code provided in pub.dev is only the entry point of the example app. If you want to check the full example project, you can find it in the repo. The project is split into multiple files for better structure and the easy_localization is the localization package used to show support for both LTR & RTL.
If you want details about how to use the parameters you can check the package docs.
Last, if you don't like the current content, you can always contribute, and provide a detailed content through a pull request.
