### ISSUE TITLE
Color issue [default]

### ISSUE THREAD

**Issue by ghost** [medyas/flutter_zoom_drawer#63]
Hey, sorry. I was using this package and I can't seem to change this color. Help would be appreciated.
From color I mean the lower shade that you guys can see (blue).
![image](https://user-images.githubusercontent.com/85259282/139494931-a39d9770-c8c5-4005-8e44-a29dc59243f5.png)
![image](https://user-images.githubusercontent.com/85259282/139495052-1e5f6963-98d7-41d8-8d6a-1b511f421920.png)

**Comment by medyas** [comment]
so you want to change the blue color ?

**Comment by ghost** [comment]
> so you want to change the blue color ?

Yes.

**Comment by medyas** [comment]
well you should check where are you creating the gradient and update the color
