### ISSUE TITLE
Lost a position of listview when sliding drawer

### ISSUE THREAD

**Issue by minhnhatvdl** [medyas/flutter_zoom_drawer#64]
Hello,
I have a home page with a listview. I have a problem when i slide a drawer.
I lost a position of listview when i do this action. The position return to the top of listview (offset 0).

Anyone has the same problem with me ?
Thank you very much for your help.

**Comment by medyas** [comment]
you could keep you scroll with PageStorageKey or using scroll notification listener and listen for scroll end and save the scroll position then provide it to the listview in scrollcontroller. You can Google for more details.

**Comment by minhnhatvdl** [comment]
I tested it with  PageStorageKey but i always have the problem.

**Comment by medyas** [comment]
@minhnhatvdl than use , also maybe keep the offset in the home screen and no tin the page it self, as it will be destroyed.

```dart

/// global variable
double _offset = 0.0;

/// Build method

NotificationListener<ScrollEndNotification>(
    onNotification: (scrollNotification) {
        // save current scroll position
       _offset = scrollNotification.metrics.pixels;
       return true;
    },
    child: ListView(
       controller: ScrollController(initialScrollOffset:  _offset ),
       // YOUR OWN CODE HERE
   )
)
```

**Comment by minhnhatvdl** [comment]
Cool thank you bro !!!
