### ISSUE TITLE
WEB view not scrolling

### ISSUE THREAD

**Issue by arungeodexia** [medyas/flutter_zoom_drawer#65]
WEB view not scrolling

**Comment by medyas** [comment]
Could you provide more details ! and reproducible code

**Comment by CatEatFishs** [comment]
I have the same proble，webView not scroll 。
--------------------------------------
flutter doctor -v：

 Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.0 at /Users/admin/develop/flutter
    • Framework revision b22742018b (6 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

----------------------------------------------------
class PageWeb extends StatefulWidget {
  const PageWeb({Key? key}) : super(key: key);

  @override
  _PageWebState createState() => _PageWebState();
}

class _PageWebState extends State<PageWeb> {
  @override
  Widget build(BuildContext context) {
    return ZoomDrawer(
      mainScreen: Container(
        child:WebView(
          initialUrl: 'https://flutter.cn',
          javascriptMode: JavascriptMode.unrestricted,
        ),
      ), cancelCallback: () {
        return true;
    }, menuScreen:  Container(),
    );
  }
}

**Comment by CatEatFishs** [comment]
I have solved the problem；
The reason is that webView scroll and ZoomDrawer GestureDetector event Sliding conflict（滑动冲突），
I set a variable to control whether the GestureDetector's onPanUpdate event is null，
-------------
```

 bool isLoadWebView;//如果是webView页面，需要置为false，否则webView的滑动会跟ZoomDrawer 的GestureDetector 产生滑动冲突

  @override
  Widget build(BuildContext context) {
    if (widget.disableGesture) return renderLayout();

    return GestureDetector(
      /// Detecting the slide amount to close the drawer in RTL & LTR
      onTapUp: (detail) {
        if (_state == DrawerState.open &&
            detail.globalPosition.dx > AdaptUtils.pxW(548)) {
          toggle();
        }
      },
      onPanUpdate: widget.isLoadWebView?(details) {
        if (_state == DrawerState.open &&
            ((details.delta.dx < -6 && !widget.isRtl) ||
                (details.delta.dx < 6 && widget.isRtl))) {
          toggle();
        }
      }:null,
      child: renderLayout(),
    );
  }
```

**Comment by CatEatFishs** [comment]
> WEB view not scrolling

加一个变量，就可以解决，
bool isLoadWebView;//如果是webView页面，需要置为false，否则webView的滑动会跟ZoomDrawer 的GestureDetector 产生滑动冲突
上面的回复已经贴了代码

**Comment by medyas** [comment]
@CatEatFishs thanks!
