### ISSUE TITLE
Navigate back and forth from drawer menu with voice over 

### ISSUE THREAD

**Issue by EinatK** [medyas/flutter_zoom_drawer#66]
Hi, 
I have an issue with not being able to easily move to the drawer menu and back when voice over is activated. 
Could you help ?

**Comment by medyas** [comment]
@EinatK  could you provide more details about the issue ? and maybe a sample code

**Comment by EinatK** [comment]
I don't have time right now to write a sample code, will try to do it soon.. the issue is when voice over is activated and you open the drawer menu the navigation doesn't continue to the drawer menu and i'm stuck on the main page. I have to actively tap on something inside the menu to move the accessibly focus which is not a good solution as a blind person won't see where to tap. 
The expected behavior should be that once opened the accessibly focus should move over automatically to the top most element in the menu and once there, left swipe (to go back) should go back to the button that opened it. 
(i assume any project will behave the same, simply enable voice over and see )

**Comment by EinatK** [comment]
@medyas I figured it out.. it does work, it just doesn't support RTL . meaning if my drawer menu is opening on the right side i need to keep swiping left until i get to the menu, which is counter intuitive.
