### ISSUE TITLE
Closing the menu by navigation works from one direction.

### ISSUE THREAD

**Issue by multi-net** [medyas/flutter_zoom_drawer#68]
When I open the menu in RTL, I can close it by pulling the main screen. But if I open it in LTR, I can't close it by pulling. I have to click on the the menu button in the appbar to close it (Bad UX). 
What's wrong?

**Comment by medyas** [comment]
@multi-net please provide a sample project

**Comment by multi-net** [comment]
`ChangeNotifierProvider(
      create: (context) => HomeProvider(),
      builder: (context, child) {
        final provider = context.watch<HomeProvider>();
        return Scaffold(
          body: ZoomDrawer(
            isRtl: provider.rtl(),
            angle: 0.0,
            slideWidth: Consts.width * .50,
            controller: provider.drawerController,
            backgroundColor: Consts.colors.primaryColor,
            openCurve: Curves.fastOutSlowIn,
            borderRadius: 60.0,
            style: DrawerStyle.Style7,
            showShadow: true,
            mainScreenScale: .3,
            mainScreen: Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: Consts.colors.accentColor,
                image: DecorationImage(
                    image: AssetImage(
                      Consts.assets.header,
                    ),
                    fit: BoxFit.fitWidth,
                    alignment: Alignment.topCenter),
              ),
              child: Column(
                children: const [
                  HomeAppBar(),
                  HomeBody(),
                ],
              ),
            ),
            menuScreen: const AppDrawer(),
          ),
        );
      },
    );`

**Comment by multi-net** [comment]
```
ChangeNotifierProvider(
      create: (context) => HomeProvider(),
      builder: (context, child) {
        final provider = context.watch<HomeProvider>();
        return Scaffold(
          body: ZoomDrawer(
            isRtl: provider.rtl(),
            angle: 0.0,
            slideWidth: Consts.width * .50,
            controller: provider.drawerController,
            backgroundColor: Consts.colors.primaryColor,
            openCurve: Curves.fastOutSlowIn,
            borderRadius: 60.0,
            style: DrawerStyle.Style7,
            showShadow: true,
            mainScreenScale: .3,
            mainScreen: Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: Consts.colors.accentColor,
                image: DecorationImage(
                    image: AssetImage(
                      Consts.assets.header,
                    ),
                    fit: BoxFit.fitWidth,
                    alignment: Alignment.topCenter),
              ),
              child: Column(
                children: const [
                  HomeAppBar(),
                  HomeBody(),
                ],
              ),
            ),
            menuScreen: const AppDrawer(),
          ),
        );
      },
    );
```

**Comment by multi-net** [comment]
`isRtl` property has this function implementation:
`bool rtl() => _localeStorage.getLocale() == 'ar' ? true : false;`

**Comment by medyas** [comment]
@multi-net just published a new version with a fix and a way for more flexibility.
`flutter_zoom_drawer: ^2.1.2`

[Changelog](https://pub.dev/packages/flutter_zoom_drawer/changelog#212) You can use `swipeOffset` to provide the user swipe gesture width(defaults to 6.0). with this, you can have a custom offset based on ur needs.
