### ISSUE TITLE
ZoomDrawer.isRTL() not working.

### ISSUE THREAD

**Issue by JeremiahKW** [medyas/flutter_zoom_drawer#69]
Inside this code is the slideWidth: row and it contains ZoomDrawer.isRTL() pasted exactly from your site. However I am getting the error under isRTL "The method 'isRTL' isn't defined for the type 'ZoomDrawer'. Try correcting the name to the name of an existing method, or defining a method named 'isRTL'."

`class _MyHomePageState extends State<MyHomePage> {
  final drawerController = ZoomDrawerController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ZoomDrawer(
        controller: drawerController,
        style: DrawerStyle.Style1,
        menuScreen: menuScreen(),
        mainScreen: mainScreen(drawerController),
        borderRadius: 24.0,
        showShadow: true,
        angle: 0.0,
        backgroundColor: Colors.grey[300]!,
        slideWidth: MediaQuery.of(context).size.width*(ZoomDrawer.isRTL()? .45: 0.65),
        openCurve: Curves.fastOutSlowIn,
        closeCurve: Curves.bounceIn,
      ),
    );
  }
}
`

**Comment by medyas** [comment]
The isRtl method has been removed. You should implement you own logic for checking this.

**Comment by JeremiahKW** [comment]
It should be removed from the flutter pub.dev then. Thanks
