### ISSUE TITLE
DrawerStyle.Style1 does not respond to border radius

### ISSUE THREAD

**Issue by Princewil** [medyas/flutter_zoom_drawer#72]
My code
![16425696581904076384782756733795](https://user-images.githubusercontent.com/40724883/150069001-76494a46-9b44-491c-bba0-ab9b1127814e.jpg)

Outcome
![Screenshot_20220119-061908](https://user-images.githubusercontent.com/40724883/150069045-a8249fcf-52cf-460e-a7e5-1a3a63711455.png)

I'm I missing something

**Comment by Princewil** [comment]
By the way, Package version=> is 2.2.1

**Comment by medyas** [comment]
@Princewil thanks, will try to work on a fix later today

**Comment by vptcnt** [comment]
I have the same problem with the last version 2.2.1
With Style1, the border radius is only during the transition Open -> Close

**Comment by medyas** [comment]
should be fixed
