### ISSUE TITLE
mainScreen rebuilds itself after opening drawer. is it normal?

### ISSUE THREAD

**Issue by shadycyan** [medyas/flutter_zoom_drawer#77]
mainScreen rebuild every time after opening drawer, is it normal?

flutter_zoom_drawer ver 2.3.1

**Comment by medyas** [comment]
@shadycyan could you try testing with the latest version `2.3.1+1`

**Comment by shadycyan** [comment]
it got fixed in this version

thanks so much for your awesome support & this amazing drawer :)

**Comment by medyas** [comment]
welcome
