### ISSUE TITLE
Close drawer on click - Feature request

### ISSUE THREAD

**Issue by YDA93** [medyas/flutter_zoom_drawer#78]
I kindly would like to raise a feature request where we can close drawer by only clicking on the widget instead of only swiping.

I tested my app and many users didn't figure out how to close the drawer.

My current workaround:
```
GestureDetector(
    onTap: () {
      if (ZoomDrawer.of(context)?.isOpen() == true) {
        ZoomDrawer.of(context)?.close();
      }
    },
    child: myWidget,
);
```

Thanks!

**Comment by medyas** [comment]
@YDA93 This is already available in the package. you can set `mainScreenTapClose` to `true` in the `ZoomDrawer` and it will allow you to close the drawer when its open by tapping on the main screen.

**Comment by YDA93** [comment]
@medyas Yes I miss that!

Would you consider absorbing the pointer too? Clicking on any button from within the screen wouldn't close the drawer.

**Comment by medyas** [comment]
its was implemented like that before, but it caused issues with main screen losing its state.
You can listen to the drawer state and rebuild your screen with a absorber if its open.

**Comment by YDA93** [comment]
@medyas Wouldn't make sense to at least include this option in the package? I can PR
