### ISSUE TITLE
mainScreen absorb pointer

### ISSUE THREAD

**Issue by YDA93** [medyas/flutter_zoom_drawer#82]
We need a way to absorb the main screen pointer while the drawer is open.

It's just not convenient to miss click another active gestures while we are trying to close drawer.

I am thinking of something like wrapping the mainScreen inside a Stack and adding another child with max width and height that listens to a  Absorbing Value notifier.

This will avoid any rebuild to mainScreen and will toggle Absorbing Value notifier same time.

**Comment by YDA93** [comment]
If it was implemented before? may I know in which commit it was removed?

**Comment by medyas** [comment]
Don't remember where exactly it was remove, but will test your implementation.
Thanks!

**Comment by YDA93** [comment]
I am not sure how it was implemented, but definitely warping mainScreenContent with AbsorbPointer isn't the right way.
Will costly rebuild the mainScreen and might cause outdated _isAbsorbing value due being called from a widget function.
