### ISSUE TITLE
mainScreenTapClose does not work when widget is interactable

### ISSUE THREAD

**Issue by AEstrellaS** [medyas/flutter_zoom_drawer#86]
When drawer is opened, tapping the main screen interacts with widgets instead of closing the drawer.

**Comment by YDA93** [comment]
> When drawer is opened, tapping the main screen interacts with widgets instead of closing the drawer.

Is fixed in https://github.com/medyas/flutter_zoom_drawer/pull/79

Just wait for next pub.dev update

**Comment by AEstrellaS** [comment]
Thank you very much for the fast response. Best,

**Comment by YDA93** [comment]
> Thank you very much for the fast response. Best,

You are welcome.
You can use my forked version for the meantime until the official package is updated:

```
  flutter_zoom_drawer:
    git: git@github.com:YDA93/flutter_zoom_drawer.git
```
