### ISSUE TITLE
Open with a swipe

### ISSUE THREAD

**Issue by RockinPaul** [medyas/flutter_zoom_drawer#9]
Is it possible to open Drawer by swiping on the content page? 
Currently, I've implemented Drawer based on your example and the only way to interact with it by swipe is closing.
Thanks for this awesome package!

**Comment by medyas** [comment]
@RockinPaul You want to open/close the drawer using swipe event(swipe right/left) ?

**Updated**
I have added the swipe to open in the example code, please check it out: [Link](https://github.com/medyas/flutter_zoom_drawer/blob/dfe636853084bd1ca28fa8860ebcc363e85e3671/example/lib/home_screen.dart#L61)

**Comment by RockinPaul** [comment]
Yep, this is exactly what I'm looking for. 
Thank you so much, you're a lifesaver!
