### ISSUE TITLE
Missing background under floating part

### ISSUE THREAD

**Issue by Paroca72** [medyas/flutter_zoom_drawer#92]
After migrate from 2.x to 3.1 missing the background under the floating part.

```
      child: ZoomDrawer(
        controller: _drawerController,
        style: DrawerStyle.defaultStyle,
        moveMenuScreen: false,
        menuScreen: const DrawerPage(),
        mainScreen: const PageSelector(),
      ),
    );
```

Where DrawerPage and PageSelector are both Scaffold wrapped in a custom Theme with own background color.
in the linked image you can see that the DrawerPage scaffold not cover anymore the whole screen with.

[Image](http://sccomponents.com/1.jpg)

Thanks for your help

**Comment by wolnynick** [comment]
That was in 3.0.0 too. If you want to fix it quickly just add color to `menuBackgroundColor`

**Comment by medyas** [comment]
@Paroca72 just set `menuScreenWidth` to `double.infinity` which will make it fill the whole page width and with this you will get the menu background color
