### ISSUE TITLE
Migrate to classes instead of function widgets

### ISSUE THREAD

**Issue by YDA93** [medyas/flutter_zoom_drawer#93]
Using function widgets is not recommended by flutter.

### References
According to https://www.youtube.com/watch?v=IOyq-eTRhvo , this affects Performance, Testability, and Accuracy

https://stackoverflow.com/questions/53234825/what-is-the-difference-between-functions-and-classes-to-create-widgets/53234826#53234826

https://github.com/flutter/flutter/issues/19269

### How should this be fixed?

I would recommend this package as start point.

https://github.com/rrousselGit/functional_widget

**Comment by medyas** [comment]
All styles are migrated to Stateless Widgets
