### ISSUE TITLE
googleMap not work after using ZoomDrawer!! 

### ISSUE THREAD

**Issue by biloo-dev** [medyas/flutter_zoom_drawer#98]
Hi guys. 
I have a map page that was working fine before using Zoom Drawer.
 When the  flutter inspector , I found that the moving event in the map did not work because of ZoomDrawer .

![2022-04-26_192122](https://user-images.githubusercontent.com/37638323/165368438-ba982bb3-ad3b-4a29-af1d-e40c2915a012.png)

![2022-04-26_192216](https://user-images.githubusercontent.com/37638323/165368506-2f810a38-92b4-4ad5-b602-a5f5d26bfa65.png)

**Comment by medyas** [comment]
@biloo-dev the package uses `GestureDetector` and is capturing the user swipe events so they won't be received in the map.
the only fix, is to fork the package and remove the events.

**Comment by JudahMcNicholl** [comment]
Sorry to raise this up again, but if you want to override these you can just add
`        scrollGesturesEnabled: true,
        gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
          new Factory<OneSequenceGestureRecognizer>(
            () => new EagerGestureRecognizer(),
          ),
        ].toSet(),`
To your GoogleMap widget, this will also disable the swipe to open on the map screen.

**Comment by thomasbradshaw** [comment]
Extra info for Google Map Users:  If the map renders but you can't scroll around, you may have to set ZoomDrawer's `disableDragGesture: true` because ZD is grabbing all the gestures.  

(Similar to closed issue [#27 ](https://github.com/medyas/flutter_zoom_drawer/issues/27))
